name: GitOps Push
description: Push changes to a GitOps repository
author: KZAP

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: git-branch
  color: green

# Define your inputs here.
inputs:
  gitops-token:
    description: GitHub token with push permissions to the GitOps repository
    required: true
  gitops-repository:
    description:
      Name of the GitOps repository (can also be specified via GITOPS_REPOSITORY
      env var)
    required: false
  gitops-branch:
    description:
      Branch name to push to in the GitOps repository (defaults to the
      repository's default branch)
    required: false
  gitops-path:
    description:
      Path in the gitops repository where all the files will be pushed (defaults
      to the current directory if not specified)
    required: false
  environment:
    description:
      The environment to deploy to (defaults to GitHub deployment environment if
      specified)
    required: true
  application-name:
    description:
      Name of the application (defaults to the current repository name if not
      specified)
    required: false
  application-manifests-path:
    description:
      Path to the application manifests directory which will be copied to the
      GitOps repository (defaults to the current directory if not specified)
    required: false
  argocd-app-helm-chart:
    description:
      Helm chart URL which is used to render our ArgoCD Application. Supports
      helm-git plugin. (default
      'git+https://github.com/kzap/gitops-push@templates/helm/argocd-app?ref=main')
    required: false
  custom-values:
    description:
      Custom values yaml for the application (defaults to an empty string if not
      specified)
    required: false

# Define your outputs here.
outputs:
  time:
    description: Time when the push was completed

runs:
  using: node24
  main: dist/index.js
