name: GitOps Push
description: Push changes to a GitOps repository
author: KZAP

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: git-branch
  color: green

# Define your inputs here.
inputs:
  gitops-token:
    description: GitHub token with push permissions to the GitOps repository
    required: true
  gitops-repository:
    description: Name of the GitOps repository (can also be specified via GITOPS_REPOSITORY env var)
    required: true
  environment:
    description: The environment to deploy to (defaults to GitHub deployment environment if specified)
    required: false

# Define your outputs here.
outputs:
  time:
    description: Time when the push was completed

runs:
  using: node20
  main: dist/index.js
